apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: yukta282003/myapp:60143d292f80a9a9e0aae674cc9e2e5da8d92354
        ports:
        - containerPort: 3000
